### ISSUE TITLE
Add argument for data cache

### ISSUE THREAD

**Issue by JakeHagen** [WGLab/PhenoSV#5]
Hello

Is there a reason the location of the data cache is fed into the program by reading `PhenoSV/lib/fpath.config` ? It would be a lot more flexible if we could specify the location with a command line argument. If you are open to this, I could add this and submit a pull request

**Comment by Karenxzr** [comment]
Hi, there's a csv file saving all feature paths and summary statistics used by phenosv codes to exact features before the inference step. Users need to change corresponding paths before running PhenoSV. To avoid confusions, this step is automatically processed by running: `python3 $current_dir/phenosv/setup.py --path "$fpath/data"` during the set up (`setup.sh`)

Because the feature file size is quite large, ~40G for the light mode, I don't expect users would change the data location often. To change a file location, users can change 'PhenoSV/lib/fpath.config' and run `phenosv/setup.py` again. 

Maybe I can update the setup.sh file and update the file location by running something like `bash setup.sh --update_path /path/to/folder`. Do you think this is what you want?

**Comment by kaichop** [comment]
I think it will be more flexible to specify data location by command line argument which overrides the information in a config file. If the argument is not specified then the location in config file can still be used.

**Comment by JakeHagen** [comment]
Thank you both for responding. Ive looked into making this change and it is a little more complicated than I first assumed. The cache directory needs to be propagated to many places in the codebase. I have opened a PR trying to accomplish this but I fear once I started testing it, I will find many places I missed.
